version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    privileged: true
    user: root
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8380:8080"
      - "50000:50000"
    volumes:
      - /home/jenkins/jenkins_home:/var/jenkins_home
      - /home/jenkins/maven/m2:/root/.m2
      - /var/run/docker.sock:/var/run/docker.sock